USE [master]
GO

CREATE DATABASE [PRN212_PROJECT_BL5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRN212_PROJECT_BL5', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PRN212_PROJECT_BL5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRN212_PROJECT_BL5_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PRN212_PROJECT_BL5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRN212_PROJECT_BL5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET  MULTI_USER 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET QUERY_STORE = ON
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PRN212_PROJECT_BL5]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Acc_Role](
	[account_id] [nvarchar](15) NOT NULL,
	[role_id] [int] NOT NULL,
	[address] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[name] [nvarchar](max) NOT NULL,
	[email] [nvarchar](max) NOT NULL,
	[phoneNumber] [nvarchar](15) NOT NULL,
	[password] [nvarchar](16) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[phoneNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cart](
	[cart_id] [int] IDENTITY(1,1) NOT NULL,
	[account_id] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_Cart] PRIMARY KEY CLUSTERED 
(
	[cart_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Food](
	[food_id] [int] IDENTITY(1,1) NOT NULL,
	[food_name] [nvarchar](max) NOT NULL,
	[typef_id] [int] NOT NULL,
	[price] [int] NOT NULL,
	[image] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Food] PRIMARY KEY CLUSTERED 
(
	[food_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Food_cart](
	[food_cart] [int] IDENTITY(1,1) NOT NULL,
	[cart_id] [int] NOT NULL,
	[food_id] [int] NOT NULL,
	[quantity] [int] NOT NULL,
 CONSTRAINT [PK_Food_cart] PRIMARY KEY CLUSTERED 
(
	[food_cart] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Food_order](
	[food_order] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NOT NULL,
	[food_id] [int] NOT NULL,
	[quantity] [int] NOT NULL,
 CONSTRAINT [PK_Food_order] PRIMARY KEY CLUSTERED 
(
	[food_order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[order_id] [int] IDENTITY(1,1) NOT NULL,
	[account_id] [nvarchar](15) NOT NULL,
	[status] [int] NOT NULL,
	[Comment] [nvarchar](max),
	[rate] [int] NOT NULL,
	[Time_oder] [datetime] NULL,
	[Time_finish] [datetime] NULL,
	[total] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[role_id] [int] NOT NULL,
	[role_define] [nvarchar](15) NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[role_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Status](
	[status_id] [int] NOT NULL,
	[name] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED 
(
	[status_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type_Food](
	[typef_id] [int] IDENTITY(1,1) NOT NULL,
	[typename] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Type_Food] PRIMARY KEY CLUSTERED 
(
	[typef_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Acc_Role]  WITH CHECK ADD  CONSTRAINT [FK_Acc_Role_Account] FOREIGN KEY([account_id])
REFERENCES [dbo].[Account] ([phoneNumber])
GO
ALTER TABLE [dbo].[Acc_Role] CHECK CONSTRAINT [FK_Acc_Role_Account]
GO
ALTER TABLE [dbo].[Acc_Role]  WITH CHECK ADD  CONSTRAINT [FK_Acc_Role_Role] FOREIGN KEY([role_id])
REFERENCES [dbo].[Role] ([role_id])
GO
ALTER TABLE [dbo].[Acc_Role] CHECK CONSTRAINT [FK_Acc_Role_Role]
GO
ALTER TABLE [dbo].[Cart]  WITH CHECK ADD  CONSTRAINT [FK_Cart_Account] FOREIGN KEY([account_id])
REFERENCES [dbo].[Account] ([phoneNumber])
GO
ALTER TABLE [dbo].[Cart] CHECK CONSTRAINT [FK_Cart_Account]
GO
ALTER TABLE [dbo].[Food]  WITH CHECK ADD  CONSTRAINT [FK_Food_Type_Food] FOREIGN KEY([typef_id])
REFERENCES [dbo].[Type_Food] ([typef_id])
GO
ALTER TABLE [dbo].[Food] CHECK CONSTRAINT [FK_Food_Type_Food]
GO
ALTER TABLE [dbo].[Food_cart]  WITH CHECK ADD  CONSTRAINT [FK_Food_cart_Cart] FOREIGN KEY([cart_id])
REFERENCES [dbo].[Cart] ([cart_id])
GO
ALTER TABLE [dbo].[Food_cart] CHECK CONSTRAINT [FK_Food_cart_Cart]
GO
ALTER TABLE [dbo].[Food_cart]  WITH CHECK ADD  CONSTRAINT [FK_Food_cart_Food] FOREIGN KEY([food_id])
REFERENCES [dbo].[Food] ([food_id])
GO
ALTER TABLE [dbo].[Food_cart] CHECK CONSTRAINT [FK_Food_cart_Food]
GO
ALTER TABLE [dbo].[Food_order]  WITH CHECK ADD  CONSTRAINT [FK_Food_order_Food] FOREIGN KEY([food_id])
REFERENCES [dbo].[Food] ([food_id])
GO
ALTER TABLE [dbo].[Food_order] CHECK CONSTRAINT [FK_Food_order_Food]
GO
ALTER TABLE [dbo].[Food_order]  WITH CHECK ADD  CONSTRAINT [FK_Food_order_Order] FOREIGN KEY([order_id])
REFERENCES [dbo].[Order] ([order_id])
GO
ALTER TABLE [dbo].[Food_order] CHECK CONSTRAINT [FK_Food_order_Order]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Account] FOREIGN KEY([account_id])
REFERENCES [dbo].[Account] ([phoneNumber])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Account]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Status] FOREIGN KEY([status])
REFERENCES [dbo].[Status] ([status_id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Status]
GO
USE [master]
GO
ALTER DATABASE [PRN212_PROJECT_BL5] SET  READ_WRITE 
GO
